name: ecosperity_ride_ws_apis
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  args: ^2.3.0
  mongo_dart: ^0.9.1
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^1.0.4
  uuid: ^3.0.7
  web_socket_channel: ^2.4.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
